services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./Panier-Malin-Amiens:/var/www/html/Panier-Malin-Amiens
      - ./Panier-Malin-Amiens/data:/var/www/html/Panier-Malin-Amiens/data
    ports:
      - "8001:8000"
    networks:
      - symfony-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: panier_malin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge

volumes:
  db_data: {}
