services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./panier_malin_amiens_api:/var/www/html/api
      - ./Panier-Malin-Amiens:/var/www/html/data
    working_dir: /var/www/html/api
    ports:
      - "8001:8000"
    networks:
      - symfony-network
    command: php-fpm
    environment:
      - PHP_EXTRA_CONFIGURE_ARGS=--enable-pdo --with-pdo-mysql=mysqlnd

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: panier_malin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80"
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge

volumes:
  db_data: {}
